# Generated by Django 5.0.6 on 2024-05-28 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Curd'), ('ML', 'Milk'), ('LS', 'Lassi'), ('PN', 'Panner'), ('GH', 'Ghee'), ('CZ', 'Cheese'), ('MC', 'Milkshake'), ('IC', 'Ice-Creams')], max_length=2),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=15)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Vinnytsia Oblast', 'Vinnytsia Oblast'), ('Volyn Oblast', 'Volyn Oblast'), ('Dnipropetrovsk Oblast', 'Dnipropetrovsk Oblast'), ('Donetsk Oblast', 'Donetsk Oblast'), ('Zhytomyr Oblast', 'Zhytomyr Oblast'), ('Zakarpattia Oblast', 'Zakarpattia Oblast'), ('Zaporizhzhia Oblast', 'Zaporizhzhia Oblast'), ('Ivano-Frankivsk Oblast', 'Ivano-Frankivsk Oblast'), ('Kyiv Oblast', 'Kyiv Oblast'), ('Kirovohrad Oblast', 'Kirovohrad Oblast'), ('Luhansk Oblast', 'Luhansk Oblast'), ('Lviv Oblast', 'Lviv Oblast'), ('Mykolaiv Oblast', 'Mykolaiv Oblast'), ('Odessa Oblast', 'Odessa Oblast'), ('Poltava Oblast', 'Poltava Oblast'), ('Rivne Oblast', 'Rivne Oblast'), ('Sumy Oblast', 'Sumy Oblast'), ('Ternopil Oblast', 'Ternopil Oblast'), ('Kharkiv Oblast', 'Kharkiv Oblast'), ('Kherson Oblast', 'Kherson Oblast'), ('Khmelnytskyi Oblast', 'Khmelnytskyi Oblast'), ('Cherkasy Oblast', 'Cherkasy Oblast'), ('Chernivtsi Oblast', 'Chernivtsi Oblast'), ('Chernihiv Oblast', 'Chernihiv Oblast'), ('Autonomous Republic of Crimea', 'Autonomous Republic of Crimea'), ('Kyiv', 'Kyiv'), ('Sevastopol', 'Sevastopol')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
